# Generated by Django 3.2.9 on 2022-01-08 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('boilerAddress', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Heatpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heatpoint', models.FloatField()),
                ('temperature', models.FloatField()),
                ('activeSensor', models.IntegerField(default=0)),
                ('heating', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Honeywell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessToken', models.CharField(max_length=60)),
                ('refreshToken', models.CharField(max_length=60)),
                ('apikey', models.CharField(max_length=60)),
                ('base64String', models.CharField(max_length=100)),
                ('refreshed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HoneywellSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('locationId', models.CharField(max_length=60)),
                ('deviceId', models.CharField(max_length=60)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('sensorAddress', models.CharField(max_length=60)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activeBoiler', models.IntegerField()),
                ('defaultBoilerTemp', models.FloatField()),
                ('defaultSensor', models.IntegerField(default=0)),
                ('scheduleGrouped', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('sensor', models.IntegerField()),
                ('temperature', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SingleDaySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField()),
                ('start', models.TimeField(default='00:00')),
                ('temperature', models.FloatField()),
                ('sensor', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data_single', to='api.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='GroupedWeekSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=20)),
                ('start', models.TimeField(default='00:00')),
                ('temperature', models.FloatField()),
                ('sensor', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data_group', to='api.sensor')),
            ],
        ),
    ]
