# Generated by Django 4.0 on 2022-01-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='openWeathermapApikey',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='setting',
            name='weatherData',
            field=models.BooleanField(default=False),
        ),
    ]
