# Generated by Django 4.0 on 2022-01-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userpincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpincode',
            name='pincode',
            field=models.CharField(default='', max_length=4),
        ),
    ]
