# Generated by Django 4.0 on 2022-01-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_userpincode_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='heatpointThreshhold',
            field=models.FloatField(default=0),
        ),
    ]
