# Generated by Django 4.0 on 2022-01-17 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_setting_heatpointthreshhold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='heatpointThreshhold',
            new_name='heatpointThreshold',
        ),
    ]
