# Generated by Django 4.0 on 2022-01-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_heatpointthreshhold_setting_heatpointthreshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThermostatData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('temperature', models.FloatField(default=0)),
                ('heatpoint', models.FloatField(default=0)),
                ('action', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Honeywell',
        ),
        migrations.DeleteModel(
            name='HoneywellSensor',
        ),
    ]
