# Generated by Django 4.0.1 on 2022-01-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_thermostatdata_delete_honeywell_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='weatherCity',
            field=models.CharField(default='', max_length=50),
        ),
    ]
