# Generated by Django 4.0.1 on 2022-01-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_setting_weathercity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='openWeathermapApikey',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='weatherCity',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='weatherData',
        ),
        migrations.AddField(
            model_name='setting',
            name='scheduleEnabled',
            field=models.BooleanField(default=True),
        ),
    ]
