# Generated by Django 3.2.8 on 2021-10-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('sensorAddress', models.CharField(max_length=60)),
                ('sensorType', models.CharField(choices=[('ARDUINO', 'Arduino'), ('HONEYWELL', 'Honeywell')], max_length=60)),
            ],
        ),
    ]
