# Generated by Django 3.2.8 on 2021-10-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_rooms_sensors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boilers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('boilerAddress', models.CharField(max_length=60)),
            ],
        ),
    ]
