# Generated by Django 3.2.8 on 2021-10-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_boilers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heatpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heatpoint', models.FloatField()),
                ('temperature', models.FloatField()),
            ],
        ),
    ]
