# Generated by Django 3.2.8 on 2021-10-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_heatpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
