# Generated by Django 3.2.8 on 2021-10-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_honeywell'),
    ]

    operations = [
        migrations.AddField(
            model_name='honeywell',
            name='refreshed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
