# Generated by Django 3.2.8 on 2021-10-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_honeywell_refreshed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoneywellSensors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('locationId', models.CharField(max_length=60)),
                ('deviceId', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='sensors',
            name='sensorType',
        ),
    ]
