# Generated by Django 3.2.8 on 2021-10-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20211025_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='honeywellsensors',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
