# Generated by Django 3.2.8 on 2021-10-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_honeywellsensors_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatpoint',
            name='heating',
            field=models.BooleanField(default=False),
        ),
    ]
