# Generated by Django 3.2.8 on 2021-10-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_heatpoint_heating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activeBoiler', models.IntegerField()),
                ('defaultBoilerTemp', models.FloatField()),
            ],
        ),
    ]
