# Generated by Django 3.2.9 on 2021-12-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_setting_schedulegrouped'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupedWeekSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('Weekday', 'Weekdays'), ('Weekend', 'Weekend')], max_length=20)),
                ('start', models.TimeField(default='00:00')),
                ('end', models.TimeField(default='00:00')),
                ('temperature', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Schedule',
            new_name='SingleDaySchedule',
        ),
    ]
