# Generated by Django 3.2.9 on 2021-12-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211220_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupedweekschedule',
            name='group',
            field=models.CharField(max_length=20),
        ),
    ]
