# Generated by Django 3.2.9 on 2021-12-27 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_groupedweekschedule_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.RenameField(
            model_name='temperaturedata',
            old_name='room',
            new_name='sensor',
        ),
    ]
