# Generated by Django 3.2.9 on 2021-12-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211227_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupedweekschedule',
            name='sensor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='singledayschedule',
            name='sensor',
            field=models.IntegerField(default=0),
        ),
    ]
