# Generated by Django 3.2.9 on 2021-12-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211227_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='defaultSensor',
            field=models.IntegerField(default=0),
        ),
    ]
