# Generated by Django 3.2.9 on 2021-12-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_setting_defaultsensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatpoint',
            name='activeSensor',
            field=models.IntegerField(default=0),
        ),
    ]
