# Generated by Django 3.2.9 on 2022-01-03 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_heatpoint_activesensor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupedweekschedule',
            name='end',
        ),
        migrations.RemoveField(
            model_name='singledayschedule',
            name='end',
        ),
    ]
