# Generated by Django 3.2.9 on 2022-01-03 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220103_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupedweekschedule',
            name='sensorId',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sensor'),
        ),
        migrations.AddField(
            model_name='singledayschedule',
            name='sensorId',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sensor'),
        ),
    ]
