# Generated by Django 3.2.9 on 2022-01-03 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220103_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupedweekschedule',
            name='sensorId',
        ),
        migrations.RemoveField(
            model_name='singledayschedule',
            name='sensorId',
        ),
        migrations.AlterField(
            model_name='groupedweekschedule',
            name='sensor',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sensor'),
        ),
        migrations.AlterField(
            model_name='singledayschedule',
            name='sensor',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sensor'),
        ),
    ]
